<<<<<<< HEAD
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Layout from '../layout/Layout'
import MainSection from '../components/main'
const inter = Inter({ subsets: ['latin'] })
=======
import { Inter } from "@next/font/google";
import Head from "next/head";
import Main from "../Layouts/Main";

const inter = Inter({ subsets: ["latin"] });
>>>>>>> xone-dev

export default function Home() {
  return (
    <>
<<<<<<< HEAD
      <Layout>
        <MainSection></MainSection>
      </Layout>
=======
      <Head>
        <title>Alpha | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-gray-50 min-h-screen">
        <Main></Main>
      </div>
>>>>>>> xone-dev
    </>
  );
}
