import { Inter } from "@next/font/google";
import Head from "next/head";
import Categories from './../pages/Categories'
import TrendingMatch from '../components/trendingMatch';
import Trending from "../components/Trending/Trending"
import Carrousel from '../components/Carrousel'
import BigBanner from '../components/BigBanner'
import ContacForm from "../components/contacForm";
import Team from "../components/team";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Alpha | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Categories />
      <Trending></Trending>
      <Carrousel></Carrousel>
      <BigBanner></BigBanner>
      <TrendingMatch />
      <Team></Team>
      <ContacForm></ContacForm>
    </>
  );
}
